### ISSUE TITLE
Cambios

### ISSUE THREAD

**Issue by fedm4** [hrchioest/Login#1]
- Los estilos del div podrías pasarlos al "form" y borrar directamente el div. 
- Hay varios estilos que se comparten entre .caja-green y .caja-gris, entonces, podriamos hacer una clase nueva, y que caja-gris solo tenga el color de background, y caja-green color de background y color de fuente, mientras que los otros estilos están en esta clase nueva, y estos tres elementos de html van a compartir esa clase. Así no repetimos el código.
- Borrar los bordes de los inputs y del boton

Todo el resto está perfecto.

**Comment by hrchioest** [comment]
@fedm4 listo hice los cambios y ya quedaron actualizados los cambios en github :)
